[package]
name = "hashing" 
version = "0.1.0"
authors = ["Ben Marsh <benjamin.marsh@mintlayer.org>"]

[workspace]
members = [
    "blake2",
    "ripemd160",
    "sha1",
    "sha2",
    "sha3",
]

[profile.dev]
opt-level = 2
